export default {
    HOME: "Home",
    PROFILE: "Profile",
    EXPLORE1: "Explore1",
    EXPLORE2: "Explore2",
    SIGNIN: "SignIn",
    SIGNUP: "SignUp",
    CHAT: "Chat",
    DASHBOARD:"Dashboard",
    DETAIL:"Detail",
    CATEGORYNAVIGATION:"CategotyNavigation",
    INBOX: "Inbox",
    PACKAGES: "Packages",
    SEARCH:"Search",
    // POST:'Post',
    ADDIMAGE:'AddImage',
    NOTIFICATION: 'Notification',
    FORGETPASS: 'Forgetpass',
    FILTER: 'Filter',
    // REVIEW:'Review',
 
}